# -*- coding: utf-8 -*-
"""Amazon_Music.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5bfZMerURv8sHgIX5hk72UfhG5pU-18

1. Data Exploration & Preprocessing
"""

import pandas as pd

df = pd.read_csv("/content/single_genre_artists.csv")

df.info()

print(df.columns)

print(df.shape)

"""Dropped unnecessary columns:

"""

import pandas as pd

df_clean = df.drop(columns=['name_song', 'name_artists', 'id_songs', 'followers',
    'popularity_songs',
    'popularity_artists',
    'id_artists', 'release_date', 'genres',
    'explicit',
    'key',
    'mode',
    'time_signature'],  errors='ignore')
print(df_clean.columns)

df_clean.to_csv("Cleaned.csv", index = False)
print("downloaded the cleaned csv")

print(df_clean.shape)

df_clean.dropna(inplace=True)
df_clean.isnull().sum()

"""Visualize distributions of key features to understand variation in values.

"""

import matplotlib.pyplot as plt

df_clean.hist(figsize=(20, 15), bins=30)
plt.suptitle("Feature Distributions", fontsize=20)

plt.tight_layout()
plt.show()

import seaborn as sns

plt.figure(figsize=(14,8))
sns.boxplot(data=df_clean)
plt.xticks(rotation=45)
plt.title("Boxplot of Features")
plt.show()

"""Visualize distributions of key features to understand variation in values.

"""

for col in df_clean.columns:
    plt.figure()
    sns.histplot(df_clean[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.show()

df_clean.describe()

"""Normalize the data"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_clean)

import pandas as pd

scaled_df = pd.DataFrame(scaled_data, columns=df_clean.columns)
print(scaled_df.describe())

"""Feature Selection"""

df_clean.columns

"""Clustering Techniques"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia.append(kmeans.inertia_)

"""Used the Elbow Method: Plot SSE (inertia) vs. k and find the "elbow."
"""

plt.figure(figsize=(8,5))
plt.plot(K_range, inertia, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia (SSE)")
plt.title("Elbow Method")
plt.show()

"""Silhouette Score to evaluate how well clusters are formed.

"""

from sklearn.metrics import silhouette_score

for k in range(2, 6):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(scaled_data)

    score = silhouette_score(scaled_data, labels)
    print(f"K={k}, Silhouette Score={score}")

"""DBSCAN (for discovering arbitrary-shaped clusters)

Cluster Evaluation and Interpretation
"""

from sklearn.cluster import KMeans

k = 3
kmeans = KMeans(n_clusters=k, random_state=42)
df_final = df_clean.copy()
df_final['cluster'] = kmeans.fit_predict(scaled_data)

from sklearn.metrics import davies_bouldin_score

# Calculate DBI using your scaled data and the predicted labels
db_index = davies_bouldin_score(scaled_data, df_final['cluster'])

print(f"Davies-Bouldin Index for K=3: {db_index:.4f}")

from sklearn.cluster import KMeans
from sklearn.metrics import davies_bouldin_score
import matplotlib.pyplot as plt

db_scores = []
K_range = range(2, 11)  # DBI requires at least 2 clusters

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(scaled_data)

    # Calculate DBI for each K
    score = davies_bouldin_score(scaled_data, labels)
    db_scores.append(score)

# Plotting the results
plt.figure(figsize=(10, 6))
plt.plot(K_range, db_scores, marker='o', color='red', linestyle='--')
plt.title('Davies-Bouldin Index for Optimal K', fontsize=14)
plt.xlabel('Number of Clusters (K)', fontsize=12)
plt.ylabel('Davies-Bouldin Index Score', fontsize=12)
plt.xticks(K_range)
plt.grid(True)
plt.savefig('dbi_plot.png')
plt.show()

"""mean values of each feature per cluster to profile clusters"""

cluster_summary = df_final.groupby('cluster').mean(numeric_only=True).round(3)
print(cluster_summary)

df['cluster'] = df_final['cluster']
df.to_csv("final_clustered_songs.csv", index=False)

df.groupby('cluster')['name_song'].head(5)

df.groupby('cluster')['genres'].value_counts().head(10)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_data = pca.fit_transform(scaled_data)

import pandas as pd

pca_df = pd.DataFrame(pca_data, columns=['PC1', 'PC2'])
pca_df['cluster'] = df_final['cluster']

"""2D scatter plots using PCA/t-SNE with color-coded cluster"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(pca_df['PC1'], pca_df['PC2'], c=pca_df['cluster'])
plt.title("Clusters Visualization (PCA)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

"""Heatmaps comparing features across clusters."""

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Calculate the mean values for each feature per cluster
# Note: Using the df_final (original scale) helps with real-world interpretation,
# but using scaled_data means for the heatmap often shows differences more clearly.
cluster_summary = df_final.groupby('cluster').mean()

# 2. Transpose the dataframe so features are rows and clusters are columns
cluster_summary_t = cluster_summary.T

# 3. Plot the Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(cluster_summary_t, annot=True, cmap='YlGnBu', fmt='.3f', linewidths=.5)

plt.title('Audio Feature Profiles by Cluster', fontsize=16)
plt.xlabel('Cluster Number', fontsize=12)
plt.ylabel('Audio Features', fontsize=12)

# Save the figure for your project report as per guidelines
plt.savefig('cluster_heatmap.png')
plt.show()

# Optional: Heatmap using scaled data for better visual contrast
scaled_summary = pd.DataFrame(scaled_data, columns=df_clean.columns)
scaled_summary['cluster'] = df_final['cluster']
scaled_plot_data = scaled_summary.groupby('cluster').mean().T

sns.heatmap(scaled_plot_data, annot=True, cmap='RdBu_r', center=0)
plt.title('Relative Feature Strength (Scaled)')

cluster_summary = df_final.groupby('cluster')[
    ['danceability', 'energy', 'acousticness',
     'instrumentalness', 'valence', 'tempo']
].mean()

import matplotlib.pyplot as plt

cluster_summary.plot(
    kind='bar',
    figsize=(12,6)
)

plt.title("Average Audio Features per Cluster")
plt.ylabel("Average Value")
plt.xlabel("Cluster")
plt.xticks(rotation=0)
plt.legend(bbox_to_anchor=(1.05, 1))
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

sns.boxplot(
    x='cluster_name',
    y='danceability',
    data=df_final
)

plt.title("Danceability Distribution by Cluster")
plt.xticks(rotation=15)
plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    x='cluster_name',
    y='tempo',
    data=df_final
)

plt.title("Tempo Distribution by Cluster")
plt.xticks(rotation=15)
plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    x='cluster_name',
    y='energy',
    data=df_final
)

plt.title("Energy Distribution by Cluster")
plt.xticks(rotation=15)
plt.show()

import pandas as pd


# 1. Calculate cluster means and overall means

cluster_means = df_final.groupby('cluster').mean(numeric_only=True)

overall_means = df_final.drop(
    columns=['cluster'],
    errors='ignore'
).mean(numeric_only=True)

# 2. Function to generate cluster names

def suggest_cluster_name(cluster_idx):

    row = cluster_means.loc[cluster_idx]

    if row['acousticness'] > overall_means['acousticness'] * 1.5:
        return "Chill/Acoustic"

    elif (
        row['energy'] > overall_means['energy']
        and row['danceability'] > 0.6
    ):
        return "High-Energy Dance"

    elif row['instrumentalness'] > overall_means['instrumentalness'] * 2:
        return "Instrumental/Focus"

    elif (
        row['valence'] > overall_means['valence']
        and row['energy'] > overall_means['energy']
    ):
        return "Upbeat/Happy"

    elif row['speechiness'] > overall_means['speechiness'] * 2:
        return "Speech-Heavy/Vocal"

    else:
        return f"Mixed Mood (Cluster {cluster_idx})"

# 3. Create cluster mapping

cluster_mapping = {
    cluster_id: suggest_cluster_name(cluster_id)
    for cluster_id in sorted(df_final['cluster'].unique())
}

# Add cluster names to df_final
df_final['cluster_name'] = df_final['cluster'].map(cluster_mapping)

# 4. Merge cluster info back into original dataframe

df['cluster'] = df_final['cluster']
df['cluster_name'] = df_final['cluster_name']

# 5. Display cluster mapping

print("\nCluster Mapping:")
print("=" * 40)

for idx, name in cluster_mapping.items():
    print(f"Cluster {idx} -> {name}")

# 6. Preview top genres in each cluster

print("\nTop Genres Per Cluster:")
print("=" * 40)

print(df.groupby('cluster')['genres'].value_counts().head(10))

# 7. Preview top tracks per cluster

for cluster in sorted(df['cluster'].unique()):

    print("\n" + "=" * 60)
    cluster_name = (df[df['cluster'] == cluster]['cluster_name'].iloc[0])

    print(f"Cluster {cluster} : {cluster_name}")
    print("=" * 60)
    top_tracks = df[df['cluster'] == cluster][[
        'name_song',
        'name_artists',
        'genres',
        'popularity_songs']].sort_values(by='popularity_songs',ascending=False).head(10)

    print(top_tracks)

# 8. Export final dataset

df.to_csv("Amazon_Music_Final_Categorized.csv",index=False)
print("Final categorized dataset exported successfully!")

# 9. Preview final dataframe

print(df.head())